@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.signbutton;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;