modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
#updateJSONURL="http://myurl.me/" #optional
issueTrackerURL="https://github.com/gigaherz/SignButton/issues" #optional
displayURL="https://github.com/gigaherz/SignButton" #optional
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="gigaherz" #optional
license="BSD (3 clause)"

[[mods]] #mandatory
modId="signbutton" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Sign Button" #mandatory
description='''
A sign that is a button
'''

[[dependencies.signbutton]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33.0,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.signbutton]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17)"
    ordering="NONE"
    side="BOTH"