modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
license="BSD (3 clause)"

[[mods]] #mandatory
modId="signbutton" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Sign Button" #mandatory
description='''
A sign that is a button
'''
#updateJSONURL="http://myurl.me/" #optional
issueTrackerURL="https://github.com/gigaherz/SignButton/issues" #optional
displayURL="https://github.com/gigaherz/SignButton" #optional
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="gigaherz" #optional

[[dependencies.signbutton]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38.0.16,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.signbutton]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"