modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
#updateJSONURL="http://myurl.me/" #optional
issueTrackerURL="https://github.com/gigaherz/SignButton/issues" #optional
displayURL="https://github.com/gigaherz/SignButton" #optional
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="gigaherz" #optional

[[mods]] #mandatory
modId="signbutton" #mandatory
version="${version}" #mandatory
displayName="Sign Button" #mandatory
description='''
A sign that is a button
'''

[[dependencies.naturaltrees]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.0.0,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.naturaltrees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,1.15)"
    ordering="NONE"
    side="BOTH"