modLoader="javafml"
loaderVersion="[44,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/SignButton/issues"

[[mods]]
modId="signbutton"
version="${file.jarVersion}"
displayName="Sign Button"
description='''
A sign that is a button
'''
displayURL="https://github.com/gigaherz/SignButton"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.signbutton]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.signbutton]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"