modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/SignButton/issues"

[[mods]]
modId="signbutton"
version="${file.jarVersion}"
displayName="Sign Button"
description='''
A sign that is a button
'''
displayURL="https://github.com/gigaherz/SignButton"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.signbutton]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.signbutton]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"