@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.signbutton.button;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;