@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.signbutton.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;